### PR TITLE
Sulaco fix1

### PR DESCRIPTION
**Pull request by Kmc2000**
WHAT THIS DOES

Adds in some fake engines sprites, they're literally the PA sprites with some tiny edits, sue me

Feel free to replace them, i felt it made engineering look less barren.

Engineering now has two AM generators, and briefing is now a fitness room.

:cl: Kmc2000
add: Briefing no longer exists, it's now a fitness room
add: Added decorative engines that do nothing

/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Fixed:

No vents in the fitness room

Random BS disposal thing that lead nowhere in the bridge

**Comment by Carbonhell** [comment]
Fitness room has a few problems
1)shutters,they're not needed anymore man
2)the cables on the left lead to nothing appaently?link them to the rightmost ones

**Comment by TalkingCactus** [comment]
Aren't AM engines multi-part structures of fuel and shielding or something?

**Comment by Kmc2000** [comment]
I read the wiki


Apparently that's it, all the shielding things are in the boxes

**Comment by Kmc2000** [comment]
ALSO cables and shutters


Will remove asap

**Comment by Kmc2000** [comment]
Fixed:

vents that went nowhere on the left side

Random shutter memes

Random cables that went nowhere

**Comment by Carbonhell** [comment]
can this be merged?

**Comment by Kmc2000** [comment]
Yes

**Comment by Carbonhell** [comment]
pr merged because the briefing change is good,but honestly i don't like both the ideas of using fake structures and the engineering design at all tbh,we'll need to improve it

**Pull request merged**
